name: infra-compose
services:
  post-db:
    image: postgres:15.4
    command: -p 5432 -c idle_session_timeout=1805000
    environment:
      POSTGRES_USER: postteller
      POSTGRES_PASSWORD: post123!
    ports:
      - "5431:5431"